### ISSUE TITLE
Cannot find module './formatter' when attempting to use the package

### ISSUE THREAD

**Issue by AlexAtHome** [jfromaniello/mac-ca#12]
It seems that only `index.js` got published. It causes an error `Cannot find module './formatter'`.

![image](https://user-images.githubusercontent.com/21964985/227864921-3c272415-77b5-4134-a153-0dbb8fdc75c4.png)

Would you, please, re-build and re-publish the package so it will have all 6 files?

**Comment by ath0mas** [comment]
I am unable to use v2 because of this same issue too.
Please @jfromaniello

**Comment by AlexAtHome** [comment]
@ath0mas, for now, you can make a `postinstall` script in your project that will `cd` into `node_modules/mac-ca` and run `npm run prepare`

**Comment by jfromaniello** [comment]
I am very sorry about this, can you try installing the just published v2.0.2?

Thank you

**Comment by AlexAtHome** [comment]
Tried both 2.0.2 and 2.0.3. Works properly now

Thank you

**Comment by ath0mas** [comment]
These updates solve the issue for me too, thanks.
